### ISSUE TITLE
Connection icon keeps on spinning!

### ISSUE THREAD

**Issue by cpascariello** [thomas-lowry/themer#13]
Hi there,
I'm in some trouble because my themer plugin keeps loading!

<img width="241" alt="Screenshot 2020-06-05 at 17 57 53" src="https://user-images.githubusercontent.com/3958216/83897711-37001600-a756-11ea-9ae1-408fc0df6da6.png">

The action I took prior to the problem was that I configured another to another jsonbin source without first resetting and now it keeps on spinnen and I can't use the plugin anymore.

Here in attach you'll find the log from the console as this can maybe help solve it or is there a way I can hard reset the plugin and start from scratch?
[www.figma.com-1591372438621.log](https://github.com/thomas-lowry/themer/files/4737211/www.figma.com-1591372438621.log)

Thanks in advance!

**Comment by cpascariello** [comment]
**!!! SOLVED !!!**
I removed the bin completely which created a connection error.
At that point the interface presented me again with the regular panel to re-configure 🙌

**Comment by AlexDemzz** [comment]
What do you mean by "remove the bin ?", i have the same issue
