### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mtzaquia** [thomas-lowry/themer#14]
Hello, there!

As I came across your plugin, it felt like a really good starting point for a project I'm currently working on in my company. That would require me to clone & modify your plugin's code for internal usage.

I couldn't find a license, so I was wondering if there are any restrictions to perform the actions mentioned above?

Thanks!

**Comment by viljamis** [comment]
@mtzaquia See https://github.com/thomas-lowry/themer/blob/master/LICENSE 

It’s MIT
