### ISSUE TITLE
Feature request - Drag to re-order themes in the list

### ISSUE THREAD

**Issue by Subcide** [thomas-lowry/themer#23]
We have 7 themes at the moment, and due to lack of "Update theme" function, when we delete/re-add a theme, it goes to the bottom of the list and the only way to get it back to where it should be is to delete and re-add all 7 themes in order.  A drag handle would be nice :)

**Comment by nachosdesign** [comment]
We have a couple of dozen themes. This would be awesome!

**Comment by yceballost** [comment]
Would be nice to have groups too!

**Comment by rob-millington** [comment]
Agree!

**Comment by thomas-lowry** [comment]
Drag to re-order is now available in the new version! Great suggestion and thank you all!
