### ISSUE TITLE
Applying is not working, I'm getting 404 error

### ISSUE THREAD

**Issue by antonijap** [thomas-lowry/themer#37]
![image](https://user-images.githubusercontent.com/12565719/151049316-e64792c7-f2d6-4a73-bf85-1f86a537ada6.png)

I see JSON in jsonbin.io and I see both themes in Themer but when I try to apply I get this error

**Comment by tstirrat** [comment]
The 404 is because the styles are not found in the team library. You need to publish those new styles.

**Comment by thomas-lowry** [comment]
This should be resolved. If these GET requests are failing, the style is either unpublished or has been deleted.
