### ISSUE TITLE
JSONBIN.io API v2 will be deprecated on 28th February 2022, will this plugin still work after?

### ISSUE THREAD

**Issue by leinardi** [thomas-lowry/themer#38]
If you login into  you get this red warning:

> We will be deprecating API v2 on 28th February, 2022. Checkout API v3 Documentation for more info.

![image](https://user-images.githubusercontent.com/273338/151337042-1dca1fd5-dd2e-4422-bc7a-50df470acf8e.png)

The documentation for the API v3 can be found here: https://jsonbin.io/api-reference

Will this plugin still work after the 28th February?

**Comment by rob-millington** [comment]
No it won't :(
