### ISSUE TITLE
Tokens with and/or without spaces

### ISSUE THREAD

**Issue by rob-millington** [thomas-lowry/themer#42]
Hi all,

We are having a few issues syncing themes and I am spotted in the json file that some tokens are saved with spaces (eg Theme / Text / Text 100) and others are saved without (eg. Theme/Text/Text 100)

Could this be causing us issues? It's impossible to see inside Figma and fixing in the JSON file doesn't seem to make much different (still not working)

For context the initial setup was done by a contract designer last year and now we are making some changes to some themes but its not working. I noticed we have also gone through V1 and are now on V2 of Themer... I wonder if thats making some issues for us too!

Cheers, Rob

**Comment by rob-millington** [comment]
For anyone having issues we managed to resolve by recreating our base theme (with the same pattern of spaces and /'s...) and then doing a Find & Replace on the JSON to marry up the format.

**Comment by thomas-lowry** [comment]
Also there is some inconsistency here with the way handles spaces in style names that I have flagged with the Figma team. Will close this one for now, thanks @rob-millington
